Default: &defaults
  database: stutor.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: stutor_test.sqlite3
  <<: *defaults

Staging:
  database: stutor_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: stutor_production.sqlite3
  poolsize: 100
  <<: *defaults
